### PR TITLE
Add missing return value

### LINKED ISSUE #161: core-sitemaps v0.2.0 renders 404-s with single.php
**Describe the bug**
When core-sitemaps plugin is disabled 404 (non-existent) URL-s return: `404.php` template

When enabled `single.php` gets rendered **with HTTP/200** for non-existent URL-s

### PR DESCRIPTION
**Pull request by swissspidy**
### Issue Number
Fixes #161

### Type of change
Please select the relevant options:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (change which improves an existing feature. E.g., performance improvement, docs update, etc.)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Steps to test

1. Go to `https://example.com/400000004444/`
1. Verify that http status is 404, not 200.

### Acceptance criteria
- [x] My code follows WordPress coding standards.
- [x] I have performed a self-review of my own code.
- [x] If the changes are visual, I have cross browser / device tested.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added test instructions that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you.

Could it be that `add_action( 'pre_handle_404'` is really `add_filter`?

**Comment by szepeviktor** [comment]
Works.

Verified, Certified, Okay!
😸

**Comment by swissspidy** [comment]
> Could it be that add_action( 'pre_handle_404' is really add_filter?
yep indeed

**Comment by szepeviktor** [comment]
My new habit is [going explicit](https://github.com/GoogleChromeLabs/wp-sitemaps/issues/161#issuecomment-618365758) at add_filter/add_action: always adding priority and number of arguments.

**Review by szepeviktor — APPROVED** [review]

**Review by pbiron — APPROVED** [review]
I can confirm the behavior reported in the issue and that this:

1. fixes the problem
2. still allows `sitemap.xml` to redirect to `wp-sitemap.xml`

**Pull request merged**
