### PR TITLE
#86 Add test coverage for API filters

### LINKED ISSUE #86: Add user documentation and test coverage for available filters.
### Description

This task is related to #25.

**Describe the solution you'd like**

For all of the implemented extensible features outlined in https://github.com/GoogleChromeLabs/wp-sitemaps/issues/25#issuecomment-557305334, we should add user documentation that shows examples of how someone would use each of the provided filters, and add test coverage to assure these filters continue working as expected.

**Additional context**
Add any other context or screenshots about the enhancement request here.

### Acceptance Criteria

- [ ] All filters listed in https://github.com/GoogleChromeLabs/wp-sitemaps/issues/25#issuecomment-557305334 have PHPUnit tests.
- [ ] User examples for all filters listed in https://github.com/GoogleChromeLabs/wp-sitemaps/issues/25#issuecomment-557305334 are included in the README file or additional docs.

### PR DESCRIPTION
**Pull request by joemcgill**
### Issue Number
Closes #86.

### Description
[T/K summary]
### Screenshots (before and after if applicable)
N/A

### Type of change
Please select the relevant options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (change which improves an existing feature. E.g., performance improvement, docs update, etc.)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Steps to test
Describe the tests required to verify your changes.
Provide instructions so the PR Tester can check functionality and also list any relevant details and / or dependencies required for your tests.

### Acceptance criteria
- [ ] My code follows WordPress coding standards.
- [ ] I have performed a self-review of my own code.
- [ ] If the changes are visual, I have cross browser / device tested.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added test instructions that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by svandragt** [comment]
PHP-linting fails on this build currently, https://travis-ci.com/GoogleChromeLabs/wp-sitemaps/jobs/287930812

**Comment by joemcgill** [comment]
Still have several tests to add to this PR before I was going to mark it for CR/merge.

**Comment by felixarntz** [comment]
I've migrated the existing tests over to the current class hierarchy (since the original tests were written a while ago, some methods had been renamed in the meantime). These tests written by @joemcgill are those migrated here: https://github.com/GoogleChromeLabs/wp-sitemaps/pull/124/commits/a652a36720684185903162657b08452e11d47270

I've also include further tests for other filters based on the issue description (https://github.com/GoogleChromeLabs/wp-sitemaps/pull/124/commits/20595c21574a8b8cba626a15f8a93286f0f2807b), as well as examples which are included in the documentation section of the readme (https://github.com/GoogleChromeLabs/wp-sitemaps/pull/124/commits/85be3f9d754e1441cd3e6c9cbce7b682be477147). While this plugin is going to be phased out once this gets merged into core, we'll be able to reuse at least parts of the docs and the code examples in an eventual dev note.

**Comment by joemcgill** [comment]
@felixarntz thanks for taking the time to update this after I had let it go stale. I think we should try to get these in. The updates look good to me.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
