### PR TITLE
Add plugin activation and deactivation hooks

### LINKED ISSUE #132: Flush rewrite rules upon plugin (de)activation
As mentioned on Slack, we might need to flush rewrite rules using `flush_rewrite_rules( false )` upon plugin activation and deactivation to prevent potential issues with rewrites and other plugins.

Related: #128

### PR DESCRIPTION
**Pull request by swissspidy**
### Issue Number

Fixes #132.

### Description

Add plugin activation and deactivation hooks to flush rewrites appropriately, to minimize conflicts with other plugins.

### Type of change
Please select the relevant options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (change which improves an existing feature. E.g., performance improvement, docs update, etc.)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Acceptance criteria
- [x] My code follows WordPress coding standards.
- [x] I have performed a self-review of my own code.
- [x] If the changes are visual, I have cross browser / device tested.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added test instructions that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by pfefferle — APPROVED** [review]

**Comment by pbiron** [comment]
I was coming to comment on this...and I noticed you just merged it a few minutes ago :-(

The activation hook works as expected, but the deactivation  hook does not.

You can see this by installing/activating the [Rewrite Rules Inspector](https://wordpress.org/plugins/rewrite-rules-inspector/) plugin.  With the sitemaps plugin active, go to `Tools > Rewrite Rules`, enter `https://example.com/sitemap.xml` (where `example.com` is the domain for your test site) in the "Match URL" field and click `Filter`.  You'll see the rule for `^wp-sitemap\.xml$`.  Then, deactivate the sitemaps plugin and click the `Filter` button again in `Tools > Rewrite Rules`.  You'll still see the rule for `^wp-sitemap\.xml$`.

First, there is no need to call `$core_sitemaps->register_rewrites();` and `$core_sitemaps->register_xsl_rewrites();`...they've already been called by the time the deactivation hook is fired.  But even if they hadn't already been called, "registering" the plugin's rewrite rules is **not** what should happen in the deactivation handler.

Second, the rewrite rules that have been added by the plugin need to be "unregistered" **before** the call to `flush_rewrite_rules()`.

Unfortunately, there is no core function/method that is the opposite of `add_rewrite_rule()` (there is a `remove_rewrite_tag()` tho) .  The only way I've found to do it is to call `unset( $wp_rewrite->extra_rules_top['^wp-sitemap\.xml$'] );`. etc.

Therefore, what I suggest is adding a couple of methods to the `Core_Sitemaps` class: `unregister_rewrites()` and `unregister_xsl_rewrites()`.  In those 2 methods, do the appropriate `unset()`s and then call those methods in the deactivation handler before the call to `flush_rewrite_rules()`.

I can do a PR for that, but wanted to have someone check my logic above first.

**Comment by pfefferle** [comment]
You are right, I +1 too fast. The `core_sitemaps_plugin_deactivation` has to simply call `flush_rewrite_rules( false );`.

**Comment by pfefferle** [comment]
When the `deactivation_hook` is called, the plugin is no longer loaded, so the rewrite rules are no longer loaded and the `flush_rewrite_rules( false );` should flush them.

**Comment by pfefferle** [comment]
`register_deactivation_hook( __FILE__, 'flush_rewrite_rules' );` should also work!?!

**Comment by swissspidy** [comment]
No idea what I was thinking 🤦‍♂ Thanks for noticing @pbiron!

@pfefferle Are you sure about that? See https://core.trac.wordpress.org/ticket/29118

**Comment by swissspidy** [comment]
> `register_deactivation_hook( __FILE__, 'flush_rewrite_rules' );` should also work

No, that performs a hard flush, which we wouldn't want

**Comment by pbiron** [comment]
> When the `deactivation_hook` is called, the plugin is no longer loaded, so the rewrite rules are no longer loaded and the `flush_rewrite_rules( false );` should flush them.

Try the `Rewrite Rules Inspector` as explained above and you'll see that it doesn't work.

**Comment by swissspidy** [comment]
Let me push another PR for this 🙂

**Comment by pbiron** [comment]
See this answer from Otto to an old WP.stackexchange question : https://wordpress.stackexchange.com/a/104106/113496, which is where I learned to `unset()` rewrite rules on deactivate before flushing.

**Comment by pfefferle** [comment]
> @pfefferle Are you sure about that? See https://core.trac.wordpress.org/ticket/29118

Hmmm... Then I have to check a lot of my plugins... :(

**Comment by pbiron** [comment]
The reason is that `WP_Rewrite::flush_rules()` does a `$this->extra_rules_top = array_merge( $this->extra_rules_top, $rules );` and by the time the deactivation hook is called `$wp_rewrite->extra_rules_top` still has the plugin's rewrite rules.

**Comment by pbiron** [comment]
The other thing is: with the activation hook, `Core_Sitemaps::init()` does **not** need to hook into `wp_loaded` and the `maybe_flush_rewrites()` method can be removed.

This is because updating the plugin when it is activate will 1) deactivate it before the update; 2) activate it after the update.  So, checking the version number to decide whether the flush rewrites is no longer necessary.

**Comment by swissspidy** [comment]
@pbiron Now that we changed the URLs from `sitemap.xml` to `wp-sitemap.xml`, the `maybe_flush_rewrites` function is very useful

**Pull request merged**
