### PR TITLE
Introduce PHPStan to CI (tests should fail!)

### PR DESCRIPTION
**Pull request by szepeviktor**
### Description
add static analysis to CI

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (change which improves an existing feature. E.g., performance improvement, docs update, etc.)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by szepeviktor** [comment]
CI will fail until my previous PR is merged.

`Cannot access property $post_modified_gmt on int|WP_Post.` is reported as the PHPStan WordPress extension does not inspect `fields` paramter
https://developer.wordpress.org/reference/classes/wp_query/#return-fields-parameter
So I could develop code for it or we put in `ignoreErrors`

**Comment by szepeviktor** [comment]
This is the current output

kép

but I've just released code to detect get_posts' return type: https://github.com/szepeviktor/phpstan-wordpress/blob/master/src/GetPostsDynamicFunctionReturnTypeExtension.php#L28

**Comment by swissspidy** [comment]
@szepeviktor Would you mind rebasing the PR / merging the current master branch?

**Comment by szepeviktor** [comment]
Done.

**Comment by swissspidy** [comment]
I am closing this one for now due to conflicts and being stale. Also, the last remaining issues will be resolved with #145.

**Comment by szepeviktor** [comment]
All right.

**Pull request closed without merging**
