### PR TITLE
Fix esc_html with translation

### PR DESCRIPTION
**Pull request by szepeviktor**
Discovered by @phpstan

### Description
Fix 2 esc_html calls with translation

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (change which improves an existing feature. E.g., performance improvement, docs update, etc.)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by swissspidy** [comment]
Why this change for exactly these 2 cases?

Note that WordPress core doesn‘t escape translations like this and as a feature plugin this project shouldn‘t either.

**Comment by szepeviktor** [comment]
There are **two parameters.** esc_html does not handle translations [esc_html__](https://developer.wordpress.org/reference/functions/esc_html__/) does. These were typos.

**Comment by swissspidy** [comment]
Gotcha! Was still early I guess 😅

**Review by swissspidy — APPROVED** [review]

**Comment by szepeviktor** [comment]
👍

**Pull request merged**
