### PR TITLE
Fix plugin deactivation

### PR DESCRIPTION
**Pull request by swissspidy**
### Issue Number

See #132, #136

### Description

See https://github.com/GoogleChromeLabs/wp-sitemaps/pull/136#issuecomment-594128540 for details. Props @pbiron

### CODE REVIEW

**Comment by pbiron** [comment]
+1 on folding `register_xsl_rewrites()` into `register_rewrites()`.

Just testing that the new PR works as expected.

**Comment by pbiron** [comment]
I think the `unregister_rewrites()` method should also call:

```
remove_rewrite_tag( '%sitemap%' );
remove_rewrite_tag( '%sub_type%' );
remove_rewrite_tag( '%stylesheet%' );
```

Other than that looks good to me.

**Comment by swissspidy** [comment]
@pbiron Rewrite tags are not persisted in the DB though, are they? So that seemed a bit unnecessary

**Comment by pbiron** [comment]
> @pbiron Rewrite tags are not persisted in the DB though, are they? So that seemed a bit unnecessary

I'm not sure...there is a prop for them in `WP_Rewrite`...but that may just be per-invocation and not persisted.

**Comment by swissspidy** [comment]
Rewrite tags are basically just placeholders for regex patterns that get replace when generating the rules. Only the rules generated by `\WP_Rewrite::rewrite_rules()` are then stored. So this seems correct to me.

**Review by pfefferle — APPROVED** [review]
thanks @pbiron for testing!

**Comment by swissspidy** [comment]
Thanks to both of you!

**Pull request merged**
